version: '0.0.2'

name: forward-edge

services:
    app:
        image: forward-edge-app:latest
        build:
            context: ./
            dockerfile: ./Dockerfile
        env_file:
            - .env.dockerdb
        ports:
            - '8080:8081'
